---
title: "Elections Mining - part 2"
author: "Shlomi Adin & Baruch Rinenberg"
date: "23 8 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r labs}
library('tidyverse')
library('dplyr')
library('reshape2')
```

```{r load}

folder_path <- "C:/Users/shlom/OneDrive/Documents/לימודים/העברית/שנה ו/סמס ב/ניתוח מאגרי מידע מאסיביים/Project/הפרוייקט - חלק 2/"

elections_21 <- read.csv(file = paste0(folder_path,"edited/env_elections_21.csv"), header = TRUE)
elections_22 <- read.csv(file = paste0(folder_path,"edited/env_elections_22.csv"), header = TRUE)
elections_23 <- read.csv(file = paste0(folder_path,"edited/env_elections_23.csv"), header = TRUE)

former_path <- "C:/Users/shlom/OneDrive/Documents/לימודים/העברית/שנה ו/סמס ב/ניתוח מאגרי מידע מאסיביים/Project/דאטא/נתונים בחירות/csv/"

```


```{r megidor_BaderOfer}

# parting the number of seats each 'Napa' has

create_electors <- function(elections, seats = 60){
  electors <- elections %>% select(c("ezor", "semel_ezor","בזב", "כשרים"))
  names(electors) <- c("ezor","semel", "BZB", "kosher")
  electors <- aggregate(. ~ ezor+semel, data=electors, FUN = sum)
  if ("מעטפות" %in% electors$ezor){electors$BZB[which(electors$ezor == "מעטפות")] <- electors$kosher[which(electors$ezor == "מעטפות")]}
  
  moded <- sum(electors$BZB)%/%seats
  electors$modeds <- electors$BZB%/%moded
  lefts <- seats - sum(electors$modeds)
  mandats <- electors$modeds
  
  for (i in 1:lefts){
    more_one <- mandats + 1
    price <- electors$BZB %/% more_one
    mandats[which.max(price)] <- mandats[which.max(price)] + 1
  }
  #print(electors)
  
  electors$mandats <- mandats
  
  if (sum(electors$mandats) != seats){print(paste("ERORR - number of electors doesn't sums to", seats))}
  return(electors)
}

```


```{r megidor_ezor}

# counting how many seats any election-list has according 'Napot'

megidor_ezor <- function(elections, seats = 60){
  electors <- create_electors(elections, seats)
  n <- ncol(elections)
  reshimot <- n - 12
  area_votes <- elections[,c(6,7,9:n)] 
  a_numbers <- aggregate(. ~ ezor+semel_ezor, data=area_votes, FUN = sum)
  a_info <- a_numbers[,c(1:6)]
  a_votes <- a_numbers[,c(7:(n-6))]
  names(a_info) <- c("ezor", "semel", "bzb", "voters", "invaild", "kosher")
  a_info$seats <- electors$mandats
  a_info$moded <- a_info$kosher %/% electors$mandats
  
  a_modeds <- a_votes
  for (reshima in 1:reshimot){
    a_modeds[,reshima] <- a_modeds[,reshima] %/% a_info$moded
  } 
  a_info$per_moded <- rowSums(a_modeds)
  
  lefts_ezor <- a_info$seats - a_info$per_moded 
  a_KM <- a_modeds
  for (ezor in 1:nrow(electors)){
    a_mandats <- a_KM[ezor,]
    for (seat in 1:lefts_ezor[ezor]){
      a_more_one <- a_mandats + 1
      a_price <- a_votes[ezor,] %/% a_more_one
      a_mandats[which.max(a_price)] <- a_mandats[which.max(a_price)] + 1
    }
    a_KM[ezor,] <- a_mandats
  }
  KM_area <- t(colSums(a_KM))
  return(KM_area)
}

```

```{r megidor_global}

# computing how many seats any election-list has according all country counting

megidor_global <- function(elections, KM_area, achuz = 0.025, seats = 60){
  n <- ncol(elections)
  reshimot <- n-12
  global_votes <- elections[,c(9:n)]
  g_info <- select(global_votes, c(1:4))
  names(g_info) <- c("bzb", "voters", "invaild", "kosher")
  g_info$chasum <- 0
  g_info <- t(colSums(g_info))
  g_numbers <- t(colSums(global_votes))
  g_votes <- t(g_numbers[,c(5:(n-8))])
  
  chasima <- achuz * g_info[4]
  
  for (miflaga in 1:ncol(g_votes)){
    if ((g_votes[miflaga]<chasima) & (KM_area[miflaga] < 3)){
      g_info[4] <- g_info[4]-g_votes[miflaga]
      g_info[5] <- g_info[5]+g_votes[miflaga]
      g_votes[miflaga] <- 0
    }
  }
  
  moded <- g_info[4] %/% seats
  g_modeds <- g_votes %/% moded
  g_lefts <- seats-sum(g_modeds)
  g_mandats <- g_modeds
  for (i in 1:g_lefts){
    g_more_one <- g_mandats +1
    g_price <- g_votes %/% g_more_one
    g_mandats[which.max(g_price)] <- g_mandats[which.max(g_price)] + 1
  }
    
  KM_global <- g_mandats
  return(KM_global)
}
```


```{r ezori_neto}

ezori_21 <- megidor_ezor(elections_21, seats =  120)
reg_21 <- regular(elections_21)
row.names(ezori_21) <- "EZORI 21"
row.names(reg_21) <- "REGULAR 21"

ezori_22 <- megidor_ezor(elections_22, seats =  120)
reg_22 <- regular(elections_22)
row.names(ezori_22) <- "EZORI 22"
row.names(reg_22) <- "REGULAR 22"

ezori_23 <- megidor_ezor(elections_23, seats =  120)
reg_23 <- regular(elections_23)
row.names(ezori_23) <- "EZORI 23"
row.names(reg_23) <- "REGULAR 23"

ezori_14 <- megidor_ezor(elections_14, seats =  120)
reg_14 <- regular(elections_14)
row.names(ezori_14) <- "EZORI 14"
row.names(reg_14) <- "REGULAR 14"

compare_21 <- data.frame(rbind(ezori_21, reg_21))
compare_22 <- data.frame(rbind(ezori_22, reg_22))
compare_23 <- data.frame(rbind(ezori_23, reg_23))
compare_14 <- data.frame(rbind(ezori_14, reg_14))

compare_21 <- compare_21 %>% select(which(colSums(compare_21) > 0 ))
compare_22 <- compare_22 %>% select(which(colSums(compare_22) > 0 ))
compare_23 <- compare_23 %>% select(which(colSums(compare_23) > 0 ))
compare_14 <- compare_14 %>% select(which(colSums(compare_14) > 0 ))

```


```{r machoz}

# counting how many seats any election-list has according Israel counties

# first, parting the number of seats each county has
 
county_electors <- function(elections, seats = 120){
  electors <- elections %>% select(c("county","בזב", "כשרים"))
  names(electors) <- c("county", "BZB", "kosher")
  electors <- aggregate(. ~ county, data=electors, FUN = sum)
  if ("מעטפות" %in% electors$county){electors$BZB[which(electors$county == "מעטפות")] <- electors$kosher[which(electors$county == "מעטפות")]}
  
  moded <- sum(electors$BZB)%/%seats
  electors$modeds <- electors$BZB%/%moded
  lefts <- seats - sum(electors$modeds)
  mandats <- electors$modeds
  
  for (i in 1:lefts){
    more_one <- mandats + 1
    price <- electors$BZB %/% more_one
    mandats[which.max(price)] <- mandats[which.max(price)] + 1
  }
  
  electors$mandats <- mandats
  if (sum(electors$mandats) != seats){print(paste("ERORR - number of electors doesn't sums to",seats))}
  return(electors)
}

# second, computing how many seats each list has in every county

machoz <- function(elections, seats = 120, achuz = 0.025){
  electors <- county_electors(elections, seats)
  n <- ncol(elections)
  reshimot <- n - 12
  machoz_votes <- elections[,c(3,9:n)] 
  m_numbers <- aggregate(. ~ county, data=machoz_votes, FUN = sum)
  m_info <- m_numbers[,c(1:5)]
  m_votes <- m_numbers[,c(6:(n-7))]
  names(m_info) <- c("county", "bzb", "voters", "invaild", "kosher")
  m_info$seats <- electors$mandats
  
  m_info$chasima <- achuz * m_info$kosher
  for (reshima in 1:ncol(m_votes)){
    for (machoz in 1: nrow(m_votes)){
      if (m_votes[machoz,reshima] < m_info$chasima[machoz]){
        m_info$invalid[machoz] <- m_info$invalid[machoz] + m_votes[machoz,reshima]
        m_info$kosher[machoz] <- m_info$kosher[machoz] - m_votes[machoz,reshima]
        m_votes[machoz,reshima] <- 0
      }
    }
  }

  m_info$moded <- m_info$kosher %/% electors$mandats
  
  m_modeds <- m_votes
  for (reshima in 1:reshimot){
    m_modeds[,reshima] <- m_modeds[,reshima] %/% m_info$moded
  } 
  m_info$per_moded <- rowSums(m_modeds)
  
  lefts_machoz <- m_info$seats - m_info$per_moded 
  m_KM <- m_modeds
  for (machoz in 1:nrow(electors)){
    m_mandats <- m_KM[machoz,]
    for (seat in 1:lefts_machoz[machoz]){
      m_more_one <- m_mandats + 1
      m_price <- m_votes[machoz,] %/% m_more_one
      m_mandats[which.max(m_price)] <- m_mandats[which.max(m_price)] + 1
    }
    m_KM[machoz,] <- m_mandats
  }

  KM_machoz <- t(colSums(m_KM))
  return(KM_machoz)
}


```

```{r Rubi}

# computing results by 'Rubi' model

ezor_rubi <- function(elections, seats = 120, table = FALSE){
  electors <- create_electors(elections, seats)
  n <- ncol(elections)
  reshimot <- n - 12
  area_votes <- elections[,c(6,7,9:n)] 
  a_numbers <- aggregate(. ~ ezor+semel_ezor, data=area_votes, FUN = sum)
  a_info <- a_numbers[,c(1:6)]
  a_votes <- a_numbers[,c(7:(n-6))]
  names(a_info) <- c("ezor", "semel", "bzb", "voters", "invaild", "kosher")
  a_info$seats <- electors$mandats
  
  a_mandats <- a_votes
  for (ezor in 1:nrow(electors)){
    best <- which.max(a_votes[ezor,])
    a_mandats[ezor,] <- 0
    a_mandats[ezor,best] <- a_info$seats[ezor]
    } 
  if (table){print(cbind(electors, a_mandats))}
  KM_area <- t(colSums(a_mandats))
  return(KM_area)
}

```


```{r operate_megidor}

# operate 'Megidor' method

achuz = 0.0325

e_21 <- megidor_ezor(elections_21)
g_21 <- megidor_global(elections_21, e_21, achuz)
KM_21 <- e_21 + g_21
reg_21 <- regular(elections_21)
row.names(KM_21) <- "MEGIDOR 21"
row.names(reg_21) <- "REGULAR 21"

e_22 <- megidor_ezor(elections_22)
g_22 <- megidor_global(elections_22, e_22, achuz)
KM_22 <- e_22 + g_22
reg_22 <- regular(elections_22)
row.names(KM_22) <- "MEGIDOR 22"
row.names(reg_22) <- "REGULAR 22"

e_23 <- megidor_ezor(elections_23)
g_23 <- megidor_global(elections_23, e_23, achuz)
KM_23 <- e_23 + g_23
reg_23 <- regular(elections_23)
row.names(KM_23) <- "MEGIDOR 23"
row.names(reg_23) <- "REGULAR 23"

compare_21 <- data.frame(rbind(KM_21, reg_21))
compare_22 <- data.frame(rbind(KM_22, reg_22))
compare_23 <- data.frame(rbind(KM_23, reg_23))
compare_21 <- compare_21 %>% select(which(colSums(compare_21) > 0 ))
compare_22 <- compare_22 %>% select(which(colSums(compare_22) > 0 ))
compare_23 <- compare_23 %>% select(which(colSums(compare_23) > 0 ))


# operate 'Megidor' for 14th Knesset

folder_path <- "C:/Users/shlom/OneDrive/Documents/לימודים/העברית/שנה ו/סמס ב/ניתוח מאגרי מידע מאסיביים/Project/הפרוייקט - חלק 2/"
electors <- create_electors(elections_21)

elections_14 <- read.csv(file = paste0(folder_path,"K14/elections_14.csv"), header = TRUE)
#k14 <- aggregate(. ~ semel_city + city, data=elections_14, FUN = sum)

achuz = 0.025

e_14 <- megidor_ezor(elections_14)
g_14 <- megidor_global(elections_14, e_14, achuz)
KM_14 <- e_14 + g_14
reg_14 <- regular(elections_14)
row.names(KM_14) <- "MEGIDOR 14"
row.names(reg_14) <- "REGULAR 14"

compare_14 <- data.frame(rbind(KM_14, reg_14))
compare_14 <- compare_14 %>% select(which(colSums(compare_14) > 0 ))



```

```{r operate_machoz}

# operate Machoz results 

m_21 <- machoz(elections_21) 
m_22 <- machoz(elections_22)
m_23 <- machoz(elections_23)
m_14 <- machoz(elections_14)

m_neto_21 <- data.frame(m_21) %>% select(which(m_21 > 0 ))
m_neto_22 <- data.frame(m_22) %>% select(which(m_22 > 0 ))
m_neto_23 <- data.frame(m_23) %>% select(which(m_23 > 0 ))
m_neto_14 <- data.frame(m_14) %>% select(which(m_14 > 0 ))

```


```{r operate_usa}

# operate Rubi model

r_21 <- ezor_rubi(elections_21, table = TRUE) 
r_22 <- ezor_rubi(elections_22, table = TRUE)
r_23 <- ezor_rubi(elections_23, table = TRUE)
r_14 <- ezor_rubi(elections_14, table = TRUE)

r_neto_21 <- data.frame(r_21) %>% select(which(r_21 > 0 ))
r_neto_22 <- data.frame(r_22) %>% select(which(r_22 > 0 ))
r_neto_23 <- data.frame(r_23) %>% select(which(r_23 > 0 ))
r_neto_14 <- data.frame(r_14) %>% select(which(r_14 > 0 ))

```


```{r emet}

# load true results and compare to all models

folder_path <- "C:/Users/shlom/OneDrive/Documents/לימודים/העברית/שנה ו/סמס ב/ניתוח מאגרי מידע מאסיביים/Project/הפרוייקט - חלק 2/"
electors <- create_electors(elections_21)

data_21 <- read.csv(file = paste0(folder_path,"נתוני אמת/21.csv"), header = TRUE)
data_22 <- read.csv(file = paste0(folder_path,"נתוני אמת/22.csv"), header = TRUE)
data_23 <- read.csv(file = paste0(folder_path,"נתוני אמת/23.csv"), header = TRUE)
data_14 <- read.csv(file = paste0(folder_path,"נתוני אמת/14.csv"), header = TRUE)

combo <- function(data, rubi, ezori, mechozi, megidor, m_napa, m_global){
  n <- nrow(data)
  names(data) <- c("List", "Letter", "Results")
  mat <- matrix(0, n, 6)
  colnames(mat) <- c("Rubani", "Ezori", "Mechozi", "Megidor", "Area", "Country")
  comb <- data.frame(mat)
  df <- cbind(data[order(data$Results),],comb)

  for (i in 1:n){
    ot <- df$Letter[i]
    if (ot %in% names(rubi)){df$Rubani[i] <- rubi[which(names(rubi) == ot)]}
    if (ot %in% colnames(ezori)){df$Ezori[i] <- ezori[which(colnames(ezori) == ot)]}
    if (ot %in% names(mechozi)){df$Mechozi[i] <- mechozi[which(names(mechozi) == ot)]}
    if (ot %in% colnames(megidor)){df$Megidor[i] <- megidor[which(colnames(megidor) == ot)]}
    if (ot %in% colnames(m_napa)){df$Area[i] <- m_napa[which(colnames(m_napa) == ot)]}
    if (ot %in% colnames(m_global)){df$Country[i] <- m_global[which(colnames(m_global) == ot)]}
  }
  return(df)
}

numerical <- function(df){
  df$Mechozi <- as.numeric(df$Mechozi)
  df$Rubani <- as.numeric(df$Rubani)
  return(df)
}

df_21 <- numerical(combo(data_21, r_neto_21, ezori_21, m_neto_21, KM_21, e_21, g_21))
df_22 <- numerical(combo(data_22, r_neto_22, ezori_22, m_neto_22, KM_22, e_22, g_22))
df_23 <- numerical(combo(data_23, r_neto_23, ezori_23, m_neto_23, KM_23, e_23, g_23))
df_14 <- numerical(combo(data_14, r_neto_14, ezori_14, m_neto_14, KM_14, e_14, g_14))


```

```{r plots}

# bar plot function

bar_compare <- function(df, colms, elec, shita, clr1, clr2){
  df <- select(df, colms)
  n <- ncol(df)
  
  dftp <- melt(df, names(df)[1], names(df)[2:n])
  names(dftp) <- c("List","Method","value")
  ggplot(dftp, aes(fill = Method, x=reorder(List, value), y=value)) + 
    geom_bar(position = "dodge2", stat="identity", width = 0.7) +
    theme(axis.text.x = element_text(angle = 45)) + 
    ggtitle(paste("True results Vs.",shita," in the",elec,"elections")) +
    xlab("Electoral lists") + 
    ylab("Seats in the parliamnet") +
    geom_text(aes(label=value), position=position_dodge(width=0.7), vjust=-0.3, cex = 2)
}


bar_compare(df_14, c(1,3,4), elec = "14th", shita = "Area - FPP ('Ezori - Rubani')")
bar_compare(df_22, c(1,3,6), elec = "22nd", shita = "County ('Mechozi')")
bar_compare(df_23, c(1,3,5), elec = "23rd", shita = "Israel NAPAs ('Ezori')")
bar_compare(df_21, c(1,3,7,9,8), elec = "21st", shita = "Megidor committee")
```

```{r dif}

# plot different in seats between tow methods

dif <- function(df, colms, col_a, col_b, elec, shita, clr1, clr2){
  dff <- select(df, colms)
  dff$Difference <- (dff[,3] - dff[,2])
  dff$Status <- 'Profit'
  for (i in 1:nrow(dff)){if (dff$Difference[i] < 0){dff$Status[i] <- 'Loss'}}
  ggplot(dff, aes(fill = Status, x=reorder(List, Difference), y=Difference)) + 
    geom_bar(width = 0.7, stat="identity") +
    theme(axis.text.x = element_text(angle = 45)) + 
    ggtitle("Difference in Seats", subtitle = paste("True results Vs.",shita," in the",elec,"elections")) +
    xlab("Electoral lists") + 
    ylab("Difference of Seats") +
    geom_text(aes(label=Difference), vjust=-0., cex = 3) +
    scale_fill_manual(values=c("red", "green"))
}


dif(df_14, c(1,3,4), 3, 4, elec = "14th", shita = "Area - FPP ('Ezori - Rubani')")
dif(df_22, c(1,3,6), 3, 6, elec = "22nd", shita = "County ('Mechozi')")
dif(df_23, c(1,3,5), 3, 5, elec = "23rd", shita = "Israel NAPAs ('Ezori')")
dif(df_21, c(1,3,7), 3, 7, elec = "21st", shita = "Megidor committee")


```
